POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Vídeo 02",
  "description": "Este é o vídeo 01",
  "duration": 100
}

###

GET http://localhost:3333/videos?search=node

###

PUT http://localhost:3333/videos/b0825e58-7852-475e-bb42-550e7a5d4d58
Content-Type: application/json

{
  "title": "Vídeo 01",
  "description": "Este é o vídeo 01 editado",
  "duration": 100
}

###

DELETE http://localhost:3333/videos/3d29b316-42ff-4043-b772-46bef8444ca3