POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Vídeo node",
  "description": "Este é o vídeo 01",
  "duration": 100
}

###

GET http://localhost:3333/videos?search=node

###

PUT http://localhost:3333/videos/7346c718-6b1a-479f-8714-45a211c55cf3
Content-Type: application/json

{
  "title": "Vídeo 01",
  "description": "Este é o vídeo 01 editado",
  "duration": 100
}

###

DELETE http://localhost:3333/videos/7346c718-6b1a-479f-8714-45a211c55cf3